# Generated by Django 3.0.3 on 2020-02-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='dd', upload_to='product-images/'),
            preserve_default=False,
        ),
    ]
