# Generated by Django 3.0.3 on 2020-02-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200226_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_png',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
